[package]
name = "higgs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
enum_dispatch = "0.3.12"
slotmap = "1.0.7"
sorted-vec = "0.8.3"

[profile.bench]
debug = true
